### ISSUE TITLE
为什么列表选择要导出的聊天列表，默认只显示大于10条的聊天记录，选择不了，点不动

### ISSUE THREAD

**Issue by lily000000** [tsycnh/WeChatExporter#15]

**Comment by tcsnhj** [comment]
我也是一样的问题

**Comment by lily000000** [comment]
求解




------------------ 原始邮件 ------------------
发件人: "tcsnhj"<notifications@github.com>; 
发送时间: 2019年7月10日(星期三) 下午2:06
收件人: "tsycnh/WeChatExporter"<WeChatExporter@noreply.github.com>; 
抄送: "我的邮箱"<1204017975@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [tsycnh/WeChatExporter] 为什么列表选择要导出的聊天列表，默认只显示大于10条的聊天记录，选择不了，点不动 (#15)




我也是一样的问题

**Comment by Jamxscape** [comment]
请问问题解决了吗，我也遇到了相同的问题

**Comment by tsycnh** [comment]
不是很理解什么意思，可以上图

**Comment by WallaceGan** [comment]
![图](https://user-images.githubusercontent.com/8207731/63212242-d3a7e780-c133-11e9-861e-6bc8563c02d8.jpg)
我也是选择不了，只展示了微信名

**Comment by tsycnh** [comment]
最新版已修复此问题。
