### ISSUE TITLE
我这里也是打开之后微信用户名点不了

### ISSUE THREAD

**Issue by elttaes** [tsycnh/WeChatExporter#18]
有几个小疑问
“Step2:安装nodejs（8.11.3版本） 下载地址：https://nodejs.org/dist/v8.11.3/node-v8.11.3-x64.msi“
这个.msi不是mac上安装的吧，我就手动找了nodejs8.11.3的mac版本
安装之后输入node -v 结果是v8.11.3
但打开nwjs里面显示的是
nw.js v0.32.1
Node v10.8.0
Chromium 68.0.3440.84
不知道是不是因为这个node版本不对导致微信用户名点不了？
我想尝试运行这个程序一两个月了，很想导出聊天记录0 0每次都是各种各样的原因失败，希望得到指点

**Comment by tsycnh** [comment]
下载链接确实写错了，已更新。nodejs版本务必保持一致，因为程序里用到了sqlite，我只编译了8.11.3版本的库。如果想用其他版本的nodejs请自行编译sqlite

**Comment by dontyang** [comment]
我现在和你的问题一样，只有微信名，没聊天记录，用鼠标点击打开nwjs 应用上显示node版本和node -v显示的版本不一样
