### ISSUE TITLE
npm install sqlite3出错，不知道是什么原因，烦请看看，感谢

### ISSUE THREAD

**Issue by WallaceGan** [tsycnh/WeChatExporter#19]
执行后出错
log 如下：
(base)  $  ~/Downloads/WeChatExporter/development   master  npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.40.1 --python=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 --registry=https://registry.npm.taobao.org

> sqlite3@4.1.0 install /Users/gun/Downloads/WeChatExporter/development/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp configure --fallback-to-build --module=/Users/gun/Downloads/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/gun/Downloads/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.40.1 --python=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7' (Error: spawn nw-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/gun/Downloads/WeChatExporter/development/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/gun/Downloads/WeChatExporter/development/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/gun/Downloads/WeChatExporter/development/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp configure --fallback-to-build --module=/Users/gun/Downloads/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/gun/Downloads/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.40.1 --python=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7' (Error: spawn nw-gyp ENOENT)
npm WARN Invalid version: "1.0"
npm WARN development No description
npm WARN development No repository field.
npm WARN development No README data
npm WARN development No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gun/.npm/_logs/2019-08-17T14_22_04_848Z-debug.log

**Comment by zx0922** [comment]
same issue

**Comment by tsycnh** [comment]
sqlite 编译问题请参考官方repo：[https://github.com/mapbox/node-sqlite3](https://github.com/mapbox/node-sqlite3)
本repo不解决sqlite编译问题
