### ISSUE TITLE
运行nwjs出现 Failed to look up NSViewBridgeFactoryHost

### ISSUE THREAD

**Issue by zhangxuehan012** [tsycnh/WeChatExporter#2]
请问这个问题该如何解决？

[2945:775:1219/005041.835430:ERROR:web_contents_view_mac.mm(487)] Failed to look up NSViewBridgeFactoryHost!

**Comment by tsycnh** [comment]
@zhangxuehan012 没遇到过这个问题，先确保版本正确：nodejs 8.11.3 nwjs 0.32.1

**Comment by zhangxuehan012** [comment]
是的 版本正确😅

________________________________

**Comment by onezyr** [comment]
必须是nodejs 8.11.3 nwjs 0.32.1吗？

**Comment by cyril-wx** [comment]
本人也踩到这个坑，确实要版本一致....
