### ISSUE TITLE
编译sqlite错误

### ISSUE THREAD

**Issue by zx0922** [tsycnh/WeChatExporter#20]
`
hahadeMacBook-Pro:development haha$ npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.40.1 --registry=https://registry.npm.taobao.org

> sqlite3@4.1.0 install /Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp configure --fallback-to-build --module=/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.40.1' (Error: spawn nw-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:77:11)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3
node-pre-gyp ERR! node -v v12.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute 'nw-gyp configure --fallback-to-build --module=/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.40.1' (Error: spawn nw-gyp ENOENT)
npm WARN Invalid version: "1.0"
npm WARN development No description
npm WARN development No repository field.
npm WARN development No README data
npm WARN development No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/haha/.npm/_logs/2019-08-27T05_34_44_194Z-debug.log

---------

hahadeMacBook-Pro:development haha$ npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.40.1

> sqlite3@4.1.0 install /Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp configure --fallback-to-build --module=/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.40.1' (Error: spawn nw-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:77:11)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3
node-pre-gyp ERR! node -v v12.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute 'nw-gyp configure --fallback-to-build --module=/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/haha/Desktop/Code/Github/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.40.1' (Error: spawn nw-gyp ENOENT)
npm WARN Invalid version: "1.0"
npm WARN development No description
npm WARN development No repository field.
npm WARN development No README data
npm WARN development No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/haha/.npm/_logs/2019-08-27T05_35_56_540Z-debug.log
`

**Comment by tsycnh** [comment]
sqlite 编译问题请参考官方repo：https://github.com/mapbox/node-sqlite3
本repo不解决sqlite编译问题

**Comment by dontyang** [comment]
我也遇到这个问题了，解决了，环境变量问题，你得保证nw-gyp在你本地任意地方可用。我重新全局安装了node-gyp

**Comment by WallaceGan** [comment]
> 我也遇到这个问题了，解决了，环境变量问题，你得保证nw-gyp在你本地任意地方可用。我重新全局安装了node-gyp

请问怎么全局安装？

**Comment by Naco** [comment]
> 我也遇到这个问题了，解决了，环境变量问题，你得保证nw-gyp在你本地任意地方可用。我重新全局安装了node-gyp

我也遇到这个问题，全局安装了 node-gyp ，还是不行，仍然是报一样的错误。

**Comment by ms1995** [comment]
doc里面有点小问题，应该是`node install -g nw-gyp`而不是`node-gyp`。

**Comment by wenzai007** [comment]
我试验了 这个   因为 我用homebrew之前装了 sqlite

npm install sqlite3 --build-from-source --sqlite=/usr/local/opt/sqlite/

如果是这种方式  根本不用指定nwjs的版本 那么sqlite3的install 和nwjs 根本无关

生成的文件名师 node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node

参考这个 安装nwjs。。。。。 如果用npm install的方式安装nwjs 会有千奇百怪的bug...   https://www.cnblogs.com/xiaochongchong/p/8677914.html
