### ISSUE TITLE
Failed to parse extension manifest

### ISSUE THREAD

**Issue by dontyang** [tsycnh/WeChatExporter#22]
### nwjsv0.40.2
_/path/to/development 目录下执行_ 

> /Applications/nwjs-v0.40.2-osx-x64/nwjs.app/Contents/MacOS/nwjs . 

_控制台提示：_

> [9353:775:0904/090428.404459:ERROR:component_loader.cc(168)] Failed to parse extension manifest.

但是应用能打开，输入document目录后，只有微信账号名。

看到代码提交是近一年前，所以又下载nwjs v0.32.3尝试了一下，出现了和https://github.com/tsycnh/WeChatExporter/issues/4  一样的错误。

> [9245:52227:0904/085232.822907:ERROR:web_database_backend.cc(113)] Cannot initialize the web database: 2

请问作者还在维护没有。

**Comment by findyy99** [comment]
请问大佬我也是跟您一样，终端提示这句，然后怎么输入docement的目录啊，可否截图指点一下，谢谢！

**Comment by tsycnh** [comment]
请仔细逐字阅读readme。如果还有问题，贴上日志再开issue。

**Comment by dontyang** [comment]
> 请问大佬我也是跟您一样，终端提示这句，然后怎么输入docement的目录啊，可否截图指点一下，谢谢！
找到你自己导出的document目录的路径就可以了啊。
![image](https://user-images.githubusercontent.com/17739470/64225925-09104b80-cf10-11e9-8007-3fc6b36ef7a9.png)
![image](https://user-images.githubusercontent.com/17739470/64225967-2cd39180-cf10-11e9-9d9a-a4e4e3475fa3.png)
![image](https://user-images.githubusercontent.com/17739470/64225971-31984580-cf10-11e9-9106-4b4f7788dc90.png)

**Comment by tsycnh** [comment]
不贴日志帮不了你。

**Comment by dontyang** [comment]
> 不贴日志帮不了你。

老哥，我刚才上面那条回复的是2楼的兄弟。

这个是我现在启动遇到的问题
![image](https://user-images.githubusercontent.com/17739470/64226163-d450c400-cf10-11e9-9424-6c2ada743f7f.png)

**Comment by dontyang** [comment]
这个是通过工具导出的日志。
![image](https://user-images.githubusercontent.com/17739470/64226211-0a8e4380-cf11-11e9-8793-402d600174fa.png)

**Comment by tsycnh** [comment]
你sqlite3模块是0.40.1，nwjs版本是0.40.2，能跑起来才怪。
要么换nwjs版本，要么自己重新编译一遍sqlite3.

**Comment by dontyang** [comment]
> 你sqlite3模块是0.40.1，nwjs版本是0.40.2，能跑起来才怪。
> 要么换nwjs版本，要么自己重新编译一遍sqlite3.

这两个版本非要一样啊，知道了，我试试nwjs 0.40.1，谢谢。
因为直接复制readme上的命令，sqllite3的版本是0.40.1，nwjs是下载的最新版本。
这个issue应该能帮忙一些人。

**Comment by tsycnh** [comment]
如果你仔细阅读了readme，根本不会有这些问题。

**Comment by dontyang** [comment]
老哥，启动还是
 [14569:775:0904/200314.225452:ERROR:component_loader.cc(168)] Failed to parse extension manifest
![image](https://user-images.githubusercontent.com/17739470/64253640-4694c900-cf50-11e9-95b8-35f5322a0fe9.png)

找了一圈没找到问题，版本都是0.40.1了。
![image](https://user-images.githubusercontent.com/17739470/64253580-26650a00-cf50-11e9-995c-a6e918162747.png)

**Comment by tsycnh** [comment]
不知道原因，你装SDK版本的nwjs看一下console吧
