### ISSUE TITLE
Can't install sqlite3  (Error: spawn nw-gyp ENOENT)

### ISSUE THREAD

**Issue by xiaxiuyang** [tsycnh/WeChatExporter#24]
NWJS Version: 0.40.1
Node Version: 10.16.3
Operating System: macOS Mojave (10.14.3)

run `npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.40.1 --python=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
and I got this error:

 node-pre-gyp WARN Using request for node-pre-gyp https download
 node-pre-gyp ERR! build error
 node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp configure --fallback-to-build --module=/Users/xiuyang/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/xiuyang/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.40.1 --python=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7' (Error: spawn nw-gyp ENOENT)

node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/xiuyang/WeChatExporter/development/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/xiuyang/WeChatExporter/development/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/xiuyang/WeChatExporter/development/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp configure --fallback-to-build --module=/Users/xiuyang/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/xiuyang/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.40.1-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.40.1 --python=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7' (Error: spawn nw-gyp ENOENT)
npm WARN WechatExporter@1.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiuyang/.npm/_logs/2019-09-19T02_38_02_626Z-debug.log

Any ideas why? Thanks!

**Comment by tsycnh** [comment]
参考：https://github.com/tsycnh/WeChatExporter/issues/20
