### ISSUE TITLE
在编译 sqlite3 时遇到错误

### ISSUE THREAD

**Issue by Naco** [tsycnh/WeChatExporter#25]
进行到 step5 时遇到如下问题：

<img width="1189" alt="屏幕快照 2019-09-28 上午3 07 44" src="https://user-images.githubusercontent.com/76217/65795694-6e68fc80-e19d-11e9-898e-5a2006ed6e04.png">

请教如何解决？

**Comment by Naco** [comment]
已在前面的Issues 中找到答案。

**Comment by wenzai007** [comment]
什么答案?? @Naco

**Comment by Naco** [comment]
呃，时间太久了，我完全忘了当时的情况，sorry。我直到最后还是没有跑起来，所以最终放弃了。现在已经有别的解决方案，例如楼月微信助手。

**Comment by wenzai007** [comment]
> 呃，时间太久了，我完全忘了当时的情况，sorry。我直到最后还是没有跑起来，所以最终放弃了。现在已经有别的解决方案，例如楼月微信助手。

好的 谢谢！
