### ISSUE TITLE
能够成功提取数据，但是查看聊天记录列表是空白

### ISSUE THREAD

**Issue by Naco** [tsycnh/WeChatExporter#26]
能够成功的分析数据并导出，但是在查看聊天记录时，列表始终是空白，求解决办法。

<img width="1106" alt="屏幕快照 2019-09-30 上午10 52 54" src="https://user-images.githubusercontent.com/76217/65851213-b39b5300-e384-11e9-9825-badc7e0d7a10.png">

<img width="903" alt="屏幕快照 2019-09-30 上午10 50 32" src="https://user-images.githubusercontent.com/76217/65851223-bac26100-e384-11e9-9c43-c092c5864580.png">

运行日志如下：
>---- Session started: Mon Sep 30 2019 13:10:27 GMT+0800 (中国标准时间) ----
> 
> [In] New entry controller constructor
> [Out] New entry controller constructor
> [In] New entry controller constructor
> [Out] New entry controller constructor
> [In] New entry controller constructor
> [Out] New entry controller constructor
> system info: 
> ProductName:	Mac OS X
> ProductVersion:	10.14.6
> BuildVersion:	18G103
> 
> node version: v10.16.3
> 
> nwjs info: 0.40.1
> sqlite3 binding: node-webkit-v0.40.1-darwin-x64
> 
> 
> ---- Log retrieved: Mon Sep 30 2019 13:11:21 GMT+0800 (中国标准时间) ----
> ---- Session duration: 00:00:53 ----

**Comment by sshpem** [comment]
same with u

**Comment by Naco** [comment]
不知道 @tsycnh 啥时候能帮忙看看……

**Comment by tsycnh** [comment]
看了，我也不知道是怎么回事。

**Comment by Naco** [comment]
> 看了，我也不知道是怎么回事。
:(
