### ISSUE TITLE
  运行nwjs时出现问题“发生个人资料错误”

### ISSUE THREAD

**Issue by zlq0318** [tsycnh/WeChatExporter#3]
报错说：
个人资料来自更高版本的NW.js, 因此无法使用。
某些功能可能无法使用，请指定其他个人资料目录或使用更高版本NW.js。

之后无法进入GUI界面。NW.js文件位置不用在WechatExplorer目录下么？

**Comment by tsycnh** [comment]
@zlq0318 NW.js 用的是0.32.1版本么，还有nodejs 8.11.3版本。
