### ISSUE TITLE
是否有办法把数据写入mac wechart？

### ISSUE THREAD

**Issue by DuskXi** [tsycnh/WeChatExporter#37]
现在很明显往手机中迁移微信聊天记录是很方便的
而想要往电脑里塞基本上没可能
这造成了win换Mac或者mac换win用户的麻烦
其实有些时候还是直接能在pc微信里查看聊天记录更好，更是有些无法同步的聊天记录是有必要在pc客户端上运行
所以我就在想是不是有可能把聊天记录直接从wx的backup文件中提取出来然后写入聊天记录

**Comment by tsycnh** [comment]
很难，涉及解密问题。
