### ISSUE TITLE
直接用 iMazing 备份的不行？

### ISSUE THREAD

**Issue by DeepenLau** [tsycnh/WeChatExporter#5]
直接用 iMazing 备份，到这里是空的
还是一定要用 itunes 的备份？
![image](https://user-images.githubusercontent.com/14030995/52609203-6763d700-2eb7-11e9-970d-0ef2132a5d89.png)

**Comment by graydove** [comment]
我也遇到了相同的问题

**Comment by tsycnh** [comment]
只要能正常导出未加密的Documents文件夹即可。
