### ISSUE TITLE
报错Use NSWindow's -titlebarAppearsTransparent=YES instead.

### ISSUE THREAD

**Issue by Gabrielvon** [tsycnh/WeChatExporter#6]
完成Step1~Step5后，

运行时弹出上面这个WARNING
```
 ✘ gabrielfeng@gwfarena  ~/Downloads/WeChatExporter/development   master ●  ~/Downloads/nwjs-v0.36.1-osx-x64/nwjs.app/Contents/MacOS/nwjs .
2019-02-22 23:59:59.616 nwjs[94550:8735316] *** WARNING: Textured window <NativeWidgetMacNSWindow: 0x7f9f886f0160> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

然后按步骤进行，这个地方没有显示聊天对象。
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/8952869/53281052-7a02c980-375d-11e9-9173-901488baeba8.png">

继续点击下一步，就一直卡在这个地方。
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/8952869/53281069-a3235a00-375d-11e9-9a4a-d6fbe6de4d68.png">

nodejs  v11.10.0
nwjs      v0.36.1 (从官网 https://nwjs.io 直接下载)

请问是什么原因呢？我用的是iMazing导出的备份。
顺便问一下这个`Use NSWindow's -titlebarAppearsTransparent=YES instead.`的错误，应该怎么修改。我在其他一些项目也遇到类似问题。

**Comment by tsycnh** [comment]
请使用nodejs 8.11.3 nwjs 0.32.1版本，其他版本暂不支持。导出方式按照项目提示里写的方法导出，用其他导出方式暂未测试过。
