### ISSUE TITLE
请问为什么在运行cd path/to/WeChatExporter时会显示No such file or directory

### ISSUE THREAD

**Issue by acxiao004** [tsycnh/WeChatExporter#7]
请问为什么在运行cd path/to/WeChatExporter时会显示No such file or directory？谢谢大佬

**Comment by tsycnh** [comment]
你直接把`cd path/to/WeChatExporter`输入命令行了？

**Comment by acxiao004** [comment]
呃，对的。不是输命令行吗？那应该如何操作呀？谢谢～

**Comment by tsycnh** [comment]
你需要cd到你本地的WeChatExporter目录，我给的只是一个示意目录。
